title: Brayden Bennett # your name (or website title) here
logo: "/images/headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Welcome to my portfolio!
  <br><br>
  I will be graduating in May 2021 with a BS in Data Analytics and a BA in Sports Business. I am currently on the job hunt for part-time internship opportunities and full-time positions after graduation!
  <br><br>
  <a href="https://www.linkedin.com/in/brayden-bennett/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
